const serverData = {
      1.1: {
            linkNumber: 1.1,
            problem: "Дайте відповідь на питання",
            testText: 'Коли стартер працює двигун провертається без зупинки?',
            linkNumberYes: 6.5,
            linkNumberNo: 1.2,
            img: null,
            video: null,
      },
      1.2: {
            linkNumber: 1.2,
            problem: "Дайте відповідь на питання",
            testText: 'Стартер провертає двигун на декілька обертів ,а потім починає крутитись в холосту, не провертаючи двигун?',
            linkNumberYes: 1.2_13_1,
            linkNumberNo: 1.2_13_0,
            img: null,
            video: null,
      },
      1.2_13_1: {
            linkNumber: `1.2_13_1${' Yes'}`,
            problem: "Дайте відповідь на питання",
            testText: 'Чути як стартер працює,але мотор не крутиться?',
            linkNumberYes: 1.4,
            linkNumberNo: 1.2,
            img: null,
            video: null,
      },
      1.2_13_0: {
            linkNumber: `1.2_13_0${' No'}`,
            problem: "Дайте відповідь на питання",
            testText: 'Чути як стартер працює,але мотор не крутиться?',
            linkNumberYes: 1.4,
            linkNumberNo: 1.3_66_1,
            img: null,
            video: null,
      },
      1.4: {
            linkNumber: 1.4,
            problem: "Дайте відповідь на питання",
            testText: 'Чути як лише прцює стартер, чи ще чути голосний гуркіт, скрегіт?',
            linkNumberYes: 6.7,
            linkNumberNo: 6.7,
            img: null,
            video: null,
      },
      1.5: {
            linkNumber: 1.5,
            problem: "Дайте відповідь на питання",
            testText: 'Зуби на стартері пошкодженні?',
            linkNumberYes: 1.9,
            linkNumberNo: 1.9,
            img: null,
            video: null,
      },
      1.7: {
            linkNumber: 1.7,
            problem: "Дайте відповідь на питання",
            testText: 'Вінець рухається окремо від маховика?',
            linkNumberYes: 2.0,
            linkNumberNo: 2.0,
            img: null,
            video: null,
      },
      1.9: {
            linkNumber: 1.9,
            problem: "Дайте відповідь на питання",
            testText: "Потрібно перевірити чи пошкоджені зуби на вінцю маховика. Поставте мітку на маховику, прокручуйте колнчастий вал та дивіться на зуби на вінцю маховика. Прокручуйте колінчастий вал поки зробите повний оберт. Зуби на вінцю маховика пошкодженні?",
            linkNumberYes: 1.7,
            linkNumberNo: 1.7,
            img: null,
            video: null,
      },
      2.0: {
            linkNumber: 2.0,
            problem: "Дайте відповідь на питання",
            testText: 'Візьміть стартер в руки, пробуйте прокрутити бендикс, в один напрямок він мусить крутити з собою якір(але щоб це зробити потрібна велика сила, тому якщо він не провертається це теж показник ,що все добре) ,а в інший напрямок мусить крутитись лише сам бендикс(обовязково мусить крутись з легким супротивом). У вашому випадку бендикс крутисться в один напрямок дуже легко, без легкого суротиву?',
            linkNumberYes: 6.9,
            linkNumberNo: 2.1,
            img: null,
            video: null,
      },
      2.1: {
            linkNumber: 2.1,
            problem: "Дайте відповідь на питання",
            testText: 'Бендикс не працює як муфта, він заблокований в обидві строни, в жодну з сторін не провертається?',
            linkNumberYes: 6.9,
            linkNumberNo: 6.9,
            img: null,
            video: null,
      },
      6.5: {
            linkNumber: 6.5,
            problem: "Дайте відповідь на питання",
            testText: 'Під час роботи стартера чути шум, жужання, скрегіт, буксування?',
            linkNumberYes: 6.7,
            linkNumberNo: 6.6,
            img: null,
            video: null,
      },
      6.6: {
            linkNumber: 6.6,
            problem: "Проблем не виявленно",
            testText: 'Можливо у вас нема проблем в даний час, або ви просто не ту діагностику провели.',
            linkNumberYes: 1.1,
            linkNumberNo: 1.1,
            img: null,
            video: null,
      },
      6.7: {
            linkNumber: 6.7,
            problem: "Вам прийдеться демонтувати стартер :D",
            testText: '',
            linkNumberYes: 6.8,
            linkNumberNo: 6.8,
            img: null,
            video: null,
      },
      6.8: {
            linkNumber: 6.8,
            problem: "Потрібно зловити момент коли стартер шумить, і тоді його демонтувати.",
            testText: '',
            linkNumberYes: 1.5,
            linkNumberNo: null,
            img: null,
            video: null,
      },
      6.9: {
            linkNumber: 6.9,
            problem: "Наступний етап, потрібно розібрати стартер.",
            testText: '',
            linkNumberYes: 7.2,
            linkNumberNo: 7.2,
            img: null,
            video: null,
      },
      7.0: {
            linkNumber: 7.0,
            problem: "Повна страка:D",
            testText: '',
            linkNumberYes: 7.0,
            linkNumberNo: 7.0,
            img: null,
            video: null,
      },
      7.2: {
            linkNumber: 7.2,
            problem: "Дайте відповідь на питання",
            testText: 'Якір у втулках має великий люфт?',
            linkNumberYes: 7.3,
            linkNumberNo: 7.3,
            img: null,
            video: null,
      },
      7.3: {
            linkNumber: 7.3,
            problem: "Дайте відповідь на питання",
            testText: 'Підшипники розвалилися, крутяться з ривками, шумлять?',
            linkNumberYes: 7.4,
            linkNumberNo: 7.4,
            img: null,
            video: null,
      },
      7.4: {
            linkNumber: 7.4,
            problem: "Дайте відповідь на питання",
            testText: 'Вимийте редуктор від мастила. В ньому відсутні зуби, присутні тріщини, пошкодження?',
            linkNumberYes: 7.0,
            linkNumberNo: 7.5,
            img: null,
            video: null,
      },
      7.5: {
            linkNumber: 7.5,
            problem: "Дайте відповідь на питання",
            testText: 'Вал в редукторі крутиться легко та без ривків?',
            linkNumberYes: 7.0,
            linkNumberNo: 7.0,
            img: null,
            video: null,
      },

}
export default serverData