import img19 from "./../img/19.png"
import img15 from "./../img/15.png"
import img78 from "./../img/78.png"
import img77 from "./../img/77.png"
import img99 from "./../img/img99.png"
import img89 from "./../img/areometr.jpg"



import video17 from "./../video/video17.mp4"
import video20 from "./../video/video20.mp4"

const serverData = {
      testCard: [
            {
                  linkNumber: 1,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: null,
                  linkNumberYes: 1.1,
                  linkNumberNo: 1.1,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Коли працює стартер, двигун провертається без зупинок? Так-означає, що стартер завжди провертає двигун без зупинок. Ні-означає, що коли стартер працює, двигун ніколи не обертається або інколи не обертається.',
                  instruction: null,
                  linkNumberYes: 6.5,
                  linkNumberNo: 1.2,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.2,
                  problem: "Дайте відповідь на питання",
                  testText: 'Стартер провертає двигун на декілька обертів ,а потім починає крутитись в холосту, перестаючи проверти двигун?',
                  instruction: '',
                  linkNumberYes: 1.2131,
                  linkNumberNo: 1.2130,
                  solutionYes: 18,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.2131,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чути як стартер працює,але мотор не крутиться?',
                  instruction: '',
                  linkNumberYes: 1.4,
                  linkNumberNo: 1.2,
                  solutionYes: 18,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.2130,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чути як стартер працює,але мотор не крутиться?',
                  instruction: '',
                  linkNumberYes: 1.4,
                  linkNumberNo: 8,
                  solutionYes: 18,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.3661,
                  problem: "Щось не так",
                  testText: 'Ви дали дві різні відповіді на одне питання, можливо ви помились або вам ця діагностика не підходить.',
                  instruction: '',
                  linkNumberYes: 1.1,
                  linkNumberNo: 1.1,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.4,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час роботи стартера чути голосний гуркіт, скрегіт?',
                  instruction: '',
                  linkNumberYes: 6.7,
                  linkNumberNo: 6.7,
                  solutionYes: 14,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 1.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Зуби на стартері пошкодженні(дивіться інструкцію)?',
                  instruction: 'Приклади пошкоджених бендиксів на фото (грані зубів можуть відрізнятись в залежності в яку сторонну крутиться бендикс)',
                  linkNumberYes: 2.0,
                  linkNumberNo: 2.0,
                  solutionYes: 15,
                  solutionNo: 1,
                  img: img15,
                  video: null,
            },
            {
                  linkNumber: 1.7,
                  problem: "Дайте відповідь на питання",
                  testText: 'У вас вінець рухається окремо від маховика ?(дивіться інструкцію)',
                  instruction: "На відео видно, що вінець з зубами крутяться окремо від маховика.",
                  linkNumberYes: 1.5,
                  linkNumberNo: 1.5,
                  solutionYes: 17,
                  solutionNo: 1,
                  img: null,
                  video: video17,
            },
            {
                  linkNumber: 1.9,
                  problem: "Дайте відповідь на питання",
                  testText: "Потрібно перевірити який стан зубів на вінцю маховика (дивіться інструкцію). Зуби на вінцю маховика пошкодженні?",
                  instruction: 'Поставте мітку на маховику, прокручуйте колінчастий вал та дивіться на зуби на вінцю маховика. Прокручуйте колінчастий вал поки зробите повний оберт. Дивіться приклади на фото. ',
                  linkNumberYes: 1.7,
                  linkNumberNo: 1.7,
                  solutionYes: 16,
                  solutionNo: 1,
                  img: img19,
                  video: null,
            },
            {
                  linkNumber: 2.0,
                  problem: "Дайте відповідь на питання",
                  testText: 'Ваш бендикс крутиться легко(дивіться іннструкцію)?',
                  instruction: 'Візьміть стартер в руки, пробуйте прокрутити бендикс, в один напрямок він мусить крутити з собою якір(але щоб це зробити потрібна велика сила, тому якщо він не провертається це теж показник ,що все добре) ,а в інший напрямок мусить крутитись лише сам бендикс(обовязково мусить крутись з легким супротивом). На відео бендикс крутиться без супротиву, це означає, що він ослаб.',
                  linkNumberYes: 7.9,
                  linkNumberNo: 2.1,
                  solutionYes: 18,
                  solutionNo: 1,
                  img: null,
                  video: video20,
            },
            {
                  linkNumber: 2.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Бендикс не працює як муфта, він заблокований в обидві строни, в жодну з сторін не провертається?',
                  instruction: '',
                  linkNumberYes: 6.9,
                  linkNumberNo: 6.9,
                  solutionYes: 19,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 6.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час роботи стартера чути шум, жужання, скрегіт, буксування?',
                  instruction: '',
                  linkNumberYes: 6.7,
                  linkNumberNo: 6.6,
                  solutionYes: 14,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 6.6,
                  problem: "Проблем не виявленно",
                  testText: 'Можливо у вас нема проблем в даний час, або ви просто не ту діагностику провели.',
                  instruction: '',
                  linkNumberYes: 1.1,
                  linkNumberNo: 1.1,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 6.7,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щоб вияснити що у вас вийшло з ладу потрібно демонтувати стартер. Вам до снаги така задача?',
                  instruction: '',
                  linkNumberYes: 6.8,
                  linkNumberNo: 7.6,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 6.8,
                  problem: "Потрібно зловити момент коли стартер шумить або не провертає двигун, і тоді його демонтувати.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 1.9,
                  linkNumberNo: 1.9,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 6.9,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щоб вияснити ,що у вас вийшло з ладу потрібно розібрати стартер. Якщо ваший стартер фірми Mitsubishi, рекомендуєм його віддати в спеціалізований сервісний центр для ремонту стартерів, адже ці стартера мають заводський дефект (тільки фірма Mitsubishi), через який він розбирається з великими проблемами. Вам до снаги завдання розібрати стартер?',
                  instruction: '',
                  linkNumberYes: 7.2,
                  linkNumberNo: 7.6,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  // this: "компонетнт з результатом"
                  linkNumber: 7.0,
                  problem: "",
                  testText: '',
                  linkNumberYes: null,
                  linkNumberNo: null,
                  solutionYes: null,
                  solutionNo: null,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чи пошкодженна ізоляція на якорі?',
                  instruction: '',
                  linkNumberYes: 7.4,
                  linkNumberNo: 7.4,
                  solutionYes: 23,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.2,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вісь у втулках має великий люфт?',
                  instruction: 'На вигляд (на око), зношені втулки мають овальний отвір',
                  linkNumberYes: 8.4,
                  linkNumberNo: 8.4,
                  solutionYes: 20,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.3,
                  problem: "Дайте відповідь на питання",
                  testText: 'Підшипники зруйновані, обертаються ривками, шумлять?',
                  instruction: '',
                  linkNumberYes: 7.7,
                  linkNumberNo: 7.7,
                  solutionYes: 21,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.4,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вимийте редуктор від мастила. В ньому відсутні зуби, присутні тріщини, пошкодження?',
                  instruction: '',
                  linkNumberYes: 7.0,
                  linkNumberNo: 7.5,
                  solutionYes: 24,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вал в редукторі крутиться легко та без ривків?',
                  instruction: '',
                  linkNumberYes: 7.0,
                  linkNumberNo: 7.0,
                  solutionYes: 1,
                  solutionNo: 25,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.6,
                  problem: "Пропонуєм Вам вернутись до нашого сервісу.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: null,
                  linkNumberNo: null,
                  solutionYes: null,
                  solutionNo: null,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 7.7,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чи є на якорі сліди тертя об статор?',
                  instruction: 'Сліди тертя блистять як метал натертий до блиску.На фото якір який терся об статор (відбликуюсть сліди тертя)',
                  linkNumberYes: 7.8,
                  linkNumberNo: 7.8,
                  solutionYes: 22,
                  solutionNo: 1,
                  img: img77,
                  video: null,
            },
            {
                  linkNumber: 7.8,
                  problem: "Дайте відповідь на питання",
                  testText: 'Магніти статора пошкодженні (дивіться інструкцію)? Якщо у вас не магніти, а катушка-чи пошкоджена ізоляція катушки?',
                  instruction: '',
                  linkNumberYes: 167,
                  linkNumberNo: 167,
                  solutionYes: 12,
                  solutionNo: 1,
                  img: img78,
                  video: null,
            },
            {
                  linkNumber: 7.9,
                  problem: "Дайте відповідь на питання",
                  testText: 'Бендикс крутиться в обидві сторони?',
                  instruction: '',
                  linkNumberYes: 6.9,
                  linkNumberNo: 6.9,
                  solutionYes: 13,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8,
                  problem: "Дайте відповідь на питання",
                  testText: 'Коли замок повернутий положення стартера, чути як стастер часто клацає (дивіться інструкцію)?',
                  instruction: 'На відео чути як працює стартер, у вас так само?',
                  linkNumberYes: 8.2,
                  linkNumberNo: 8.1,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Коли замок повернутий положення вмикання стартера, на один поворот ключа чути як стастер один раз клацне (дивіться інструкцію)?',
                  instruction: 'На відео стартер вмикають три рази. Стартер чути голосно, якщо клацає реле в блоці запобіжників то це буде тихо',
                  linkNumberYes: 8.2,
                  linkNumberNo: 1.3661,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8.2,
                  problem: "Перше за все рекомендуєм зробити діагностику акумулятора",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 8.3,
                  linkNumberNo: 8.3,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8.3,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 178,
                  linkNumberNo: 178,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8.4,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вилка редуктора ціла?',
                  instruction: '',
                  linkNumberYes: 8.5,
                  linkNumberNo: 8.5,
                  solutionYes: 1,
                  solutionNo: 26,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вилка переміщає бендикс по валу легко?',
                  instruction: '',
                  linkNumberYes: 7.3,
                  linkNumberNo: 7.3,
                  solutionYes: 1,
                  solutionNo: 27,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 8.6,
                  problem: "Дайте відповідь на питання",
                  testText: 'Напруга акумулятора меньша 12 вольт?',
                  instruction: '',
                  linkNumberYes: 87,
                  linkNumberNo: 87,
                  solutionYes: 28,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 87,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час пуску двигуна, напруга на акумуляторі опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 88,
                  linkNumberNo: 88,
                  solutionYes: 29,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 88,
                  problem: "Дайте відповідь на питання",
                  testText: 'Акумулятор має можливість обслуговування?',
                  instruction: '',
                  linkNumberYes: 89,
                  linkNumberNo: 939088,
                  solutionYes: 1,
                  solutionNo: 30,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 89,
                  problem: "Дайте відповідь на питання",
                  testText: 'У вас є ареометр?',
                  instruction: '',
                  linkNumberYes: 91,
                  linkNumberNo: 90,
                  solutionYes: 1,
                  solutionNo: 63,
                  img: img89,
                  video: null,
            },
            {
                  linkNumber: 90,
                  problem: "Дайте відповідь на питання",
                  testText: 'У вас є в наявності клізма та прозора посудина?',
                  instruction: '',
                  linkNumberYes: 91,
                  linkNumberNo: 939088,
                  solutionYes: 1,
                  solutionNo: 63,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 91,
                  problem: "Потрібно збовтати електроліт так, щоб підняти осад з дна",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 92,
                  linkNumberNo: 92,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 92,
                  problem: "Дайте відповідь на питання",
                  testText: 'Відкачайте електроліт так щоб було видно чи він прозорий, як джерельна водичка (зробіть 10 відкачак/закачок). Електроліт Прозорий?',
                  instruction: 'Мутний електроліт має грязний, коричневий відтінок (бульбашки на прозорість не впливають).',
                  linkNumberYes: 93,
                  linkNumberNo: 939088,
                  solutionYes: 1,
                  solutionNo: 31,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 93,
                  problem: "Зарядіть акумулятор і після цього продовжуйте діагностику",
                  testText: 'Я правильно зарядити акумулятор? У нас є стаття як це зробити.',
                  instruction: '',
                  linkNumberYes: 94,
                  linkNumberNo: 94,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 939088,
                  problem: "Зарядіть акумулятор і після цього продовжуйте діагностику",
                  testText: 'Я правильно зарядити акумулятор? У нас є стаття як це зробити.',
                  instruction: '',
                  linkNumberYes: 95,
                  linkNumberNo: 95,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 94,
                  problem: "Дайте відповідь на питання",
                  testText: 'Відкачайте електроліт так щоб було видно чи він прозорий, як джерельна водичка (зробіть 10 відкачак/закачок). Електроліт Прозорий?',
                  instruction: 'Мутний електроліт має грязний, коричневий відтінок (бульбашки на прозорість не впливають).',
                  linkNumberYes: 95,
                  linkNumberNo: 95,
                  solutionYes: 1,
                  solutionNo: 32,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 95,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час пуску двигуна, напруга на акумуляторі опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 96,
                  linkNumberNo: 96,
                  solutionYes: 34,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 96,
                  problem: "Зробіть 7 запусків двигуна.",
                  testText: ' Під час 8го пуску двигуна, напруга на акумуляторі опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 33,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 97,
                  problem: "Дайте відповідь на питяння",
                  testText: 'Напруга на акумуляторі була меньше 13.9 вольт (дивіься інструкцію)?',
                  instruction: 'Запустіть двигун, перевіряйте на пругу на акумуляторі на таких режимах роботи: всі споживачі виключені; включене ближнє світло фар та вентиллятор пічки на максимум на холостих обертах; включене ближнє світло фар та вентиллятор пічки на максимум на 2тис обертах; ',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 34,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 98,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 99,
                  linkNumberNo: 99,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 99,
                  problem: "Всі тести проводяться на запущеному двигуні за допомогою мультиметра.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 100,
                  linkNumberNo: 100,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: img99,
                  video: null,
            },
            {
                  linkNumber: 100,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 101,
                  linkNumberNo: 103,
                  solutionYes: 1,
                  solutionNo: 39,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 101,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 102,
                  solutionYes: 1,
                  solutionNo: 40,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 102,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум. Підніміть оберти двигуна до 2тис.",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 104,
                  solutionYes: 46,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 103,
                  problem: "Вимкніть навантаження і скиньте оберти двигуна до холостих.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 104,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 41,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 104,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 106,
                  linkNumberNo: 105,
                  solutionYes: 1,
                  solutionNo: 42,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 105,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум. Підніміть оберти двигуна до 2тис.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 43,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 106,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між плюсовим виводом генератора і мінусовою клемою акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 107,
                  linkNumberNo: 107,
                  solutionYes: 47,
                  solutionNo: 44,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 107,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між корпусом генератора і плюсовою клемою акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 48,
                  solutionNo: 45,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 108,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 179,
                  linkNumberNo: 179,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 109,
                  problem: "Запустіть двигун",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 117,
                  linkNumberNo: 111,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 110,
                  problem: "Запустіть двигун. Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Натяжний механізм приводного ремня підскакує?',
                  instruction: '',
                  linkNumberYes: 112,
                  linkNumberNo: 113,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 111,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 117111,
                  solutionYes: 49,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 112,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум. Підніміть оберти двигуна до 2х тис.",
                  testText: 'Натяжний механізм приводного ремня підскакує?',
                  instruction: '',
                  linkNumberYes: 113,
                  linkNumberNo: 113,
                  solutionYes: 1,
                  solutionNo: 59,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 113,
                  problem: "Дайте відповідь на питання:",
                  testText: 'При збільшенні обертів двигуна шум збільшується?',
                  instruction: '',
                  linkNumberYes: 114,
                  linkNumberNo: 114113,
                  solutionYes: 51,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 113117,
                  problem: "Дайте відповідь на питання:",
                  testText: 'При збільшенні обертів двигуна шум збільшується?',
                  instruction: '',
                  linkNumberYes: 115117,
                  linkNumberNo: 114117,
                  solutionYes: 51,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 113117111,
                  problem: "Дайте відповідь на питання:",
                  testText: 'При збільшенні обертів двигуна шум збільшується?',
                  instruction: '',
                  linkNumberYes: 114117111,
                  linkNumberNo: 114117111,
                  solutionYes: 51,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 114,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шум є тільки на холостих обертах?',
                  instruction: '',
                  linkNumberYes: 115,
                  linkNumberNo: 115,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 114113,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шум є тільки на холостих обертах?',
                  instruction: '',
                  linkNumberYes: 52,
                  linkNumberNo: 7.0,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 114117,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шум є тільки на холостих обертах?',
                  instruction: '',
                  linkNumberYes: 125,
                  linkNumberNo: 7.0,
                  solutionYes: 52,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 114117111,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шум є тільки на холостих обертах?',
                  instruction: '',
                  linkNumberYes: 115,
                  linkNumberNo: 115,
                  solutionYes: 52,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 115,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щоб вияснити що у вас вийшло з ладу потрібно демонтувати приводний ремінь. Вам до снаги така задача?',
                  instruction: '',
                  linkNumberYes: 116,
                  linkNumberNo: 7.6,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 115117,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щоб вияснити що у вас вийшло з ладу потрібно демонтувати приводний ремінь. Вам до снаги така задача?',
                  instruction: '',
                  linkNumberYes: 123,
                  linkNumberNo: 7.6,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 116,
                  problem: "Попередження!!! Наступний спосіб варварський, але якщо все робити акуратно проблем не буде (дивіться інструкцію).",
                  testText: '',
                  instruction: 'Вставте в генератор викрутку так щоб вона не торкалась обмотки статора і крепко заблокувала якір генератора в нерухомому стані. Спробуйте покрутити генератор за шків. Шків мусить в одну сторону крутитися, а в іншу ні.',
                  linkNumberYes: 119,
                  linkNumberNo: 119,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 117,
                  problem: "Дайте відповідь на питання:",
                  testText: 'У вас на генераторі стоїть обгонна муфта? Відповідь "ні" означатиме, що у вас стоїть звичайтий шків.',
                  instruction: '',
                  linkNumberYes: 110,
                  linkNumberNo: 113117,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 117111,
                  problem: "Дайте відповідь на питання:",
                  testText: 'У вас на генераторі стоїть обгонна муфта? Відповідь "ні" означатиме, що у вас стоїть звичайтий шків.',
                  instruction: '',
                  linkNumberYes: 113117111,
                  linkNumberNo: 7.0,
                  solutionYes: 53,
                  solutionNo: 50,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 118,
                  problem: "Дайте відповідь на питання:",
                  testText: 'У вас на двигуні стоїть механзм, який натягує привідний ремінь автомвтично? Відповідь "ні" означатиме, що у вас стоїть механізм, за допомогою якого, потрібно підтягувати ремінь вручну.',
                  instruction: '',
                  linkNumberYes: 7.0,
                  linkNumberNo: 7.0,
                  solutionYes: 1,
                  solutionNo: 62,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 119,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків працює нормально?',
                  instruction: '',
                  linkNumberYes: 123,
                  linkNumberNo: 120,
                  solutionYes: 54,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 120,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків заблокований в обидві сторони?',
                  instruction: '',
                  linkNumberYes: 123,
                  linkNumberNo: 121,
                  solutionYes: 55,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 121,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків обертається в обидві сторони?',
                  instruction: '',
                  linkNumberYes: 124,
                  linkNumberNo: 122,
                  solutionYes: 56,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 122,
                  problem: "Ми перерахували всі види поломок шківа, і у Вас жодної не виявленно, в той час Ви відповіли що він несправний.",
                  testText: 'Пройдіть тести ще один раз.',
                  instruction: '',
                  linkNumberYes: 116,
                  linkNumberNo: 116,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 123,
                  problem: "Крутаніть генератор якомога швидше, і послухайтте як він крутиться.",
                  testText: 'Генератор шумить?',
                  instruction: '',
                  linkNumberYes: 124,
                  linkNumberNo: 124,
                  solutionYes: 57,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 124,
                  problem: "Крутаніть обводні ролики для ремня. Також вони не мусять мати люфт.",
                  testText: 'Вони шулять або мають люфт?',
                  instruction: '',
                  linkNumberYes: 7.0,
                  linkNumberNo: 7.0,
                  solutionYes: 58,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 125,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків генератора стертий?',
                  instruction: '',
                  linkNumberYes: 126,
                  linkNumberNo: 126,
                  solutionYes: 60,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 126,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Приводний ремінь пошкоджений?',
                  instruction: '',
                  linkNumberYes: 118,
                  linkNumberNo: 118,
                  solutionYes: 61,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 127,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 129,
                  linkNumberNo: 129,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 128,
                  problem: "Для дефектовки гнератор демонтується з двигуна лише коли ви його перевірили і вияснили, що він не заряджає акумулятор, або для профілактики. Також після вияснення, що всі сигнали до штекера надходять.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 127,
                  linkNumberNo: 127,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 129,
                  problem: "Крутаніть генератор якомога швидше, і послухайтте як він крутиться.",
                  testText: 'Генератор шумить?',
                  instruction: '',
                  linkNumberYes: 130,
                  linkNumberNo: 130,
                  solutionYes: 57,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 130,
                  problem: "Акуратно розберіть генератор.",
                  testText: 'Вам до снаги така задача?',
                  instruction: '',
                  linkNumberYes: 131,
                  linkNumberNo: 7.6,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 131,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Глибина зносу колектора більше ніж 0.6 мм?',
                  instruction: '',
                  linkNumberYes: 132,
                  linkNumberNo: 132,
                  solutionYes: 68,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 132,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Щітки терлись в колектор?',
                  instruction: '',
                  linkNumberYes: 134,
                  linkNumberNo: 134,
                  solutionYes: 1,
                  solutionNo: 3,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 133,
                  problem: "Візьміть підшипник в руку, потрясіть ним біля вуха",
                  testText: 'В підшипнику щось брящить?',
                  instruction: '',
                  linkNumberYes: 143,
                  linkNumberNo: 143,
                  solutionYes: 4,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 134,
                  problem: "Дайте відповідь на питання:",
                  testText: 'У вас на генераторі стоїть обгонна муфта? Відповідь "ні" означатиме, що у вас стоїть звичайтий шків.',
                  instruction: '',
                  linkNumberYes: 135,
                  linkNumberNo: 136,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 135,
                  problem: "Тримайте якір рукою та пробуйте крутити шківа",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 137,
                  linkNumberNo: 137,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 136,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків генератора стертий?',
                  instruction: '',
                  linkNumberYes: 141,
                  linkNumberNo: 141,
                  solutionYes: 60,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 137,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків працює нормально?',
                  instruction: '',
                  linkNumberYes: 141,
                  linkNumberNo: 138,
                  solutionYes: 54,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 138,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків заблокований в обидві сторони?',
                  instruction: '',
                  linkNumberYes: 141,
                  linkNumberNo: 139,
                  solutionYes: 55,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 139,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Шків обертається в обидві сторони?',
                  instruction: '',
                  linkNumberYes: 141,
                  linkNumberNo: 140,
                  solutionYes: 56,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 140,
                  problem: "Ми перерахували всі види поломок шківа, і у Вас жодної не виявленно, в той час Ви відповіли що він несправний.",
                  testText: 'Пройдіть тести ще один раз.',
                  instruction: '',
                  linkNumberYes: 134,
                  linkNumberNo: 134,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 141,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Статор пошкоджений?',
                  instruction: '',
                  linkNumberYes: 142,
                  linkNumberNo: 142,
                  solutionYes: 5,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 142,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Є сліди що діодний міст згорів?',
                  instruction: '',
                  linkNumberYes: 133,
                  linkNumberNo: 133,
                  solutionYes: 6,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 143,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Катушка якоря ціла?',
                  instruction: 'Два кільця на колекторі мають продзвонюватись між собою.',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 6,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 144,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 145,
                  linkNumberNo: 145,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 145,
                  problem: "Всі тести проводяться на запущеному двигуні за допомогою мультиметра.",
                  testText: 'У Вас є мультиметр?',
                  instruction: '',
                  linkNumberYes: 146,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 78,
                  img: img99,
                  video: null,
            },
            {
                  linkNumber: 146,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 147,
                  linkNumberNo: 148,
                  solutionYes: 1,
                  solutionNo: 39,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 147,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 153,
                  solutionYes: 1,
                  solutionNo: 40,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 148,
                  problem: "Вимкніть навантаження і скиньте оберти двигуна до холостих.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 149,
                  linkNumberNo: 155,
                  solutionYes: 1,
                  solutionNo: 41,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 149,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 151,
                  linkNumberNo: 150,
                  solutionYes: 1,
                  solutionNo: 42,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 150,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум. Підніміть оберти двигуна до 2тис.",
                  testText: 'Напруга між плюсовим виводом генератора і корпусом генератора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 43,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 151,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між плюсовим виводом генератора і мінусовою клемою акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 152,
                  linkNumberNo: 152,
                  solutionYes: 47,
                  solutionNo: 44,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 152,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум.",
                  testText: 'Напруга між корпусом генератора і плюсовою клемою акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 48,
                  solutionNo: 45,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 153,
                  problem: "Включіть навантаження: ближнє світло фар та вентилятор пічки на максимум. Підніміть оберти двигуна до 2тис.",
                  testText: 'Напруга на контактах акумулятора в межах 13.9 - 14.9 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 149,
                  solutionYes: 46,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 154,
                  problem: "Зніміть штекер з генератора",
                  testText: 'Лампочка на щитку приладів погасла?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 156,
                  solutionYes: 7,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 155,
                  problem: "Дайте відповідь на питання:",
                  testText: 'Лампочка акумулятора на щитку приладів світиться?',
                  instruction: '',
                  linkNumberYes: 154,
                  linkNumberNo: 156,
                  solutionYes: 1,
                  solutionNo: 8,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 156,
                  problem: "Потрібно знайти схему підключення генератора.",
                  testText: 'Спробувати запустити генератор імітуючи, що штекер підєднаний (підєднати власну схему до генератора). Генератор запустився?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 9,
                  solutionNo: 10,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 157,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 180,
                  linkNumberNo: 180,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 158,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час спроби пуску двигуна, напруга на акумуляторі опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 159,
                  linkNumberNo: 160,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 159,
                  problem: "Схоже у Вас поганий акумулятор",
                  testText: 'Проведем спочатку діагностику акумулятора',
                  instruction: '',
                  linkNumberYes: 86,
                  linkNumberNo: 86,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 160,
                  problem: "Дайте відповідь на питання",
                  testText: 'Напруга під час спроби пуску між залізною частиною двигуна і плюсовою клемою акумулятора опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 161,
                  solutionYes: 11,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 161,
                  problem: "Дайте відповідь на питання",
                  testText: 'Сигнал (+) поясвляється на малій клемі стартера коли повернути замок в положення пуску двигуна?',
                  instruction: '',
                  linkNumberYes: 162161,
                  linkNumberNo: 162,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 162,
                  problem: "Вимкніть передачу!! Візьміть любий провід довжиною від 20 см і за допомогою нього подайте + від товстої клеми акумулятора до малої клеми.",
                  testText: 'Стартер запрацював?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 64,
                  solutionNo: 65,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 162161,
                  problem: "Вимкніть передачу!! Візьміть любий провід довжиною від 20 см і за допомогою нього подайте + від товстої клеми стартера до малої клеми.",
                  testText: 'Стартер запрацював?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 67,
                  solutionNo: 66,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 163,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 181,
                  linkNumberNo: 181,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 164,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час спроби пуску двигуна, напруга на акумуляторі опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 159,
                  linkNumberNo: 165,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 165,
                  problem: "Дайте відповідь на питання",
                  testText: 'Напруга під час спроби пуску між залізною частиною двигуна і плюсовою клемою акумулятора опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 11,
                  solutionNo: 69,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 166,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 1.5,
                  linkNumberNo: 1.5,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 167,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щітки терлись?',
                  instruction: '',
                  linkNumberYes: 168,
                  linkNumberNo: 168,
                  solutionYes: 1,
                  solutionNo: 70,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 168,
                  problem: "Дайте відповідь на питання",
                  testText: 'Якор пошкоджений?',
                  instruction: '',
                  linkNumberYes: 169,
                  linkNumberNo: 169,
                  solutionYes: 71,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 169,
                  problem: "Дайте відповідь на питання",
                  testText: 'Втягуюче має робочий хід?',
                  instruction: '',
                  linkNumberYes: 7.1,
                  linkNumberNo: 7.1,
                  solutionYes: 1,
                  solutionNo: 72,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 170,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може привезти до неправильних результатів діагностики.",
                  testText: '',
                  instruction: '',
                  linkNumberYes: 177,
                  linkNumberNo: 177,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 171,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час спроби пуску двигуна, напруга на акумуляторі опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 159,
                  linkNumberNo: 172,
                  solutionYes: 1,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 172,
                  problem: "Дайте відповідь на питання",
                  testText: 'Напруга під час спроби пуску між залізною частиною двигуна і плюсовою клемою акумулятора опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 173,
                  solutionYes: 11,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 173,
                  problem: "Дайте відповідь на питання",
                  testText: 'Напруга під час спроби пуску між залізною частиною двигуна і плюсовою товстою клемою стартера опускалась меньше 11 вольт?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 174,
                  solutionYes: 73,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 174,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чи появлялась напруга під час спроби пуску між залізною частиною двигуна і шиною стартера?',
                  instruction: '',
                  linkNumberYes: 175,
                  linkNumberNo: 175174,
                  solutionYes: 1,
                  solutionNo: 74,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 175,
                  problem: "Вимкніть передачу!! Спробуйте якось меремкнути два товстих болта на стартері між собою ",
                  testText: 'Стартер запрацював?',
                  instruction: '',
                  linkNumberYes: 176,
                  linkNumberNo: 7,
                  solutionYes: 75,
                  solutionNo: 76,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 175174,
                  problem: "Вимкніть передачу!! Спробуйте якось меремкнути два товстих болта на стартері між собою ",
                  testText: 'Стартер запрацював?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 75,
                  solutionNo: 76,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 176,
                  problem: "Вимкніть передачу!! Візьміть любий провід довжиною від 20 см і за допомогою нього подайте + від товстої клеми стартера до малої клеми.",
                  testText: 'Стартер запрацював?',
                  instruction: '',
                  linkNumberYes: 7,
                  linkNumberNo: 7,
                  solutionYes: 77,
                  solutionNo: 1,
                  img: null,
                  video: null,
            },
            {
                  linkNumber: 177,
                  problem: "Тести проводяться за допомогою мультиметра.",
                  testText: 'У Вас є мультиметр?',
                  instruction: '',
                  linkNumberYes: 171,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 78,
                  img: img99,
                  video: null,
            },
            {
                  linkNumber: 178,
                  problem: "Тести проводяться за допомогою мультиметра.",
                  testText: 'У Вас є мультиметр?',
                  instruction: '',
                  linkNumberYes: 8.6,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 78,
                  img: img99,
                  video: null,
            },
            {
                  linkNumber: 179,
                  problem: "Тести проводяться за допомогою мультиметра.",
                  testText: 'У Вас є мультиметр?',
                  instruction: '',
                  linkNumberYes: 109,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 78,
                  img: img99,
                  video: null,
            },
            {
                  linkNumber: 180,
                  problem: "Тести проводяться за допомогою мультиметра.",
                  testText: 'У Вас є мультиметр?',
                  instruction: '',
                  linkNumberYes: 158,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 78,
                  img: img99,
                  video: null,
            },
            {
                  linkNumber: 181,
                  problem: "Тести проводяться за допомогою мультиметра.",
                  testText: 'У Вас є мультиметр?',
                  instruction: '',
                  linkNumberYes: 164,
                  linkNumberNo: 7,
                  solutionYes: 1,
                  solutionNo: 78,
                  img: img99,
                  video: null,
            },

      ],
      resaultDiagnostic: [
            {
                  id: 1,
                  text: '',
                  solution: false,
                  //заглушка
            },
            {
                  id: 2,
                  text: '',
                  solution: false,
                  //одна відповідь яка ніколи не міняється
            },
            {
                  id: 3,
                  text: 'Замініть щітки, скоріш за все зарядки не було через це.',
                  solution: false,
            },
            {
                  id: 4,
                  text: 'Підшипники вже зношені, замініть їх.',
                  solution: false,
            },
            {
                  id: 5,
                  text: 'Статор пошкоджений, це найдорожча частина генератора, можливо дешевше найти інший генератор.',
                  solution: false,
            },
            {
                  id: 6,
                  text: 'Діодний міст потрібно замінити.',
                  solution: false,
            },
            {
                  id: 7,
                  text: 'Лампочку на щитку риладів засвічує генератор, це означає що генератор має якісь проблеми.',
                  solution: false,
            },
            {
                  id: 8,
                  text: 'Перевірте чи лампочка акумулятора хоч коли небудь засвічується. Вона має вмикатись коли запалювання увімкнене та гаснути коли двигун запустився.',
                  solution: false,
            },
            {
                  id: 9,
                  text: 'Якщо генератор запускається з вашою схемою, значить схема автомобіля не парцює потрібним чином. Перевірте щоб всі сигнали на штекер надходили.',
                  solution: false,
            },
            {
                  id: 10,
                  text: 'Генератор не справний, потрібно робити демонтаж та дефекторвку. У нас є діагностика генератора.',
                  solution: false,
            },
            {
                  id: 11,
                  text: 'У Вас поганий провід/клема який зєднує корпус двигуна з мінусовою клемою акумулятора. Усуньте цю проблему, або проложіть свій новий провід додатково. Якщо проблема з пуском не пропаде пройдіть діагностику ще раз.',
                  solution: false,
            },
            {
                  id: 12,
                  text: 'Якщо пошкоджені магніти - замінити цілий статор, якщо пошкоджена ізоляція катушки - розібрати статор, відновити ізоляцію (є ризик, що стане гірше навіть якщо ізоляцію відновити. Після розборки статора змінює форму і через це починає сильно чиркати якір.) рекомендовано замінити статор повністю.',
                  solution: false,
            },
            {
                  id: 13,
                  text: 'Бендикс не працює як муфта, він пропускає в обидві сторони. Його потрібно замінити.',
                  solution: false,
            },
            {
                  id: 14,
                  text: 'Приділіть особливу увагу, зубам на бендиксі та вінцю маховика, вони не мусять бути пошкодженні. Також перевірте редуктор ,підшипники, та втулки.',
                  solution: false,
            },
            {
                  id: 15,
                  text: 'На бендиксі пошкоджені зуби, його потрібно заміннити (якщо вам шкода грошей або немає запчастин а ви впевнені що муфта тримає навантаження і проблема лише в поганих зубах: просто загостріть їх, але ви повинні знати який мають вигляд цілі зуби) .',
                  solution: false,
            },
            {
                  id: 16,
                  text: 'Пошкоджені зуби на вінцю маховика, потрібно замінити вінець маховика або весь маховик з вінцем разом.',
                  solution: false,
            },
            {
                  id: 17,
                  text: 'Вінець відділився від маховика. Таке буває дуууже рідко. Потрібно замінити маховик з вінцем разом, або приварити вінець до маховика.',
                  solution: false,
            },
            {
                  id: 18,
                  text: 'Є підозра що бендикс дуже зношений, його потрібно замінити щоб перестрахуватись.',
                  solution: false,
            },
            {
                  id: 19,
                  text: 'Бендикс заклинив, можливо в нього потрапила вода. Потрібно його замінити.',
                  solution: false,
            },
            {
                  id: 20,
                  text: 'У втулках вісь має великий люфт, втулки потрібно замінити.',
                  solution: false,
            },
            {
                  id: 21,
                  text: 'Підшипники пошкодженні, їх потрібно замінити.',
                  solution: false,
            },
            {
                  id: 22,
                  text: 'На якорі є сліди тертя об статор,якщо ви ще не перевірили втулки і підшипники то зробіть це.',
                  solution: false,
            },
            {
                  id: 23,
                  text: 'На якорі пошкодженна ізоляція, через це стартер може повільно працювати, може працювати з перебоями, або не працювати взагалі. Якір потрібно замінити.',
                  solution: false,
            },
            {
                  id: 24,
                  text: 'Редуктор пошкоджений, його потрібно замінити.',
                  solution: false,
            },
            {
                  id: 25,
                  text: 'Потрібно вичистити кожеш зуб редуктора, поки вал не буде крутитись легко без ривків. Якщо не вдається це зробити - замінити редуктор.',
                  solution: false,
            },
            {
                  id: 26,
                  text: 'Потрібно замінити вилку стартера',
                  solution: false,
            },
            {
                  id: 27,
                  text: 'Потрібно вичистити від мастила вал стартера, середечник втягуючого, якщо бендикс всеодно погано ковзає по валу- перевірити шліци на валі по яким ходить бендикс. Зробити все щоб бендикс ковзав по валу без зусиль (мастило не використовувати).',
                  solution: false,
            },
            {
                  id: 28,
                  text: 'На початку діагностики, беручи до уваги напругу акумулятора, він був розряджений.',
                  solution: false,
            },
            {
                  id: 29,
                  text: 'На початку діагностики, беручи до уваги напругу акумулятора під час пуску двигуна, він не витримував навантаження роботи стартера.',
                  solution: false,
            },
            {
                  id: 30,
                  text: 'Нажаль, через те, що акумуляятор не має можливість його обслуговувати, достовірно сказати який в нього стан неможливо. В обслуговуємих акумуляторах є можливість дослідити стан електроліту та пластин в середині. У вашому випадку вибракувати акумулятор можливо лише по загальним ознакам падіння напруги під час пуску двигуна, без доказів несправності. Якщо в результатах діагностики не виявлено більше проблем, це може означати, що з вашою батареєю все гаразд.',
                  solution: false,
            },
            {
                  id: 31,
                  text: 'Електроліт був мутний ще до зарядки, це означає що акумулятор руйнуватися в середині (руйнуються пластини) вже давно. Відновленню такий АКБ не підлягає (заміна електроліта не допоможе бо проблема не в ньому). Рекомендуєм замінити батарею.',
                  solution: false,
            },
            {
                  id: 32,
                  text: 'Електроліт став мутний після зарядки, це означає що акумулятор почав руйнуватися в середині (руйнуються пластини) недавно. Відновленню не підлягає (заміна електроліта не допоможе бо проблема не в ньому). Рекомендуєм замінити батарею.',
                  solution: false,
            },
            {
                  id: 33,
                  text: 'Після зарядки акумулятор швидко розряджається. Причини: зруйновані пластини, батарея меньшої емності ніж висзначенно заводом, вона бракована.',
                  solution: false,
            },
            {
                  id: 34,
                  text: 'Після зарядки акумулятор так і не витримує навантаження.Причини: зруйновані пластини, акумулятор не зарядився, батарея меньшої емності ніж висзначенно заводом, заводський брак.',
                  solution: false,
            },
            {
                  id: 35,
                  text: 'На акумуляторі мала пруга під час роботи двигуна, він не проживе так довго (потрібно усунути цю проблему). Рекомендуєм пройти діагностику генератора з проблемою: "Малий заряд на акумуляторі "  ',
                  solution: false,
            },
            {
                  id: 36,
                  text: 'На автомобілі погана маса (перемичка між двигуном і акумулятором). Напруга губиться від генератора до акумулятора.',
                  solution: false,
            },
            {
                  id: 37,
                  text: 'На автомобілі поганий плюсовий провід від генератора до акумулятора. Напруга губиться від генератора до акумулятора.',
                  solution: false,
            },
            {
                  id: 38,
                  text: 'Генератор не справляється з нагрузкою. Причини: генератор не справний; генератор малопотужний; акумулятор розряджений, або стоїть більшої ємності ніж визначено заводом; ремінь генератора не натягнутий (можливий писк ремня, а також шків буде нагріватись після роботи);',
                  solution: false,
            },
            {
                  id: 39,
                  text: 'Напруга на акумуляторі без навантаження на холостих обертах мала. Акумулятор не зараяджається повною мірою, він довго не проживе.',
                  solution: false,
            },
            {
                  id: 40,
                  text: 'Напруга на акумуляторі з навантаженням на холостих обертах мала. Акумулятор не зараяджається повною мірою, він довго не проживе.',
                  solution: false,
            },
            {
                  id: 41,
                  text: 'Напруга на генераторі без навантаження на холостих обертах мала. Акумулятор не зараяджається повною мірою, він довго не проживе. Рекомендовано зробити профілактику генератора.',
                  solution: false,
            },
            {
                  id: 42,
                  text: 'Напруга на генераторі з навантаженням на холостих обертах мала. Причини: генератор не справний; генератор малопотужний; акумулятор розряджений, або стоїть більшої ємності ніж визначено заводом; ремінь генератора не натягнутий (можливий писк ремня, а також шків буде нагріватись після роботи). Акумулятор не зараяджається повною мірою, він довго не проживе. Рекомендовано зробити профілактику генератора.',
                  solution: false,
            },
            {
                  id: 43,
                  text: 'Напруга на генераторі з навантаженням на 2тис обертах мала. Акумулятор не зараяджається повною мірою, він довго не проживе. Рекомендовано зробити профілактику генератора.',
                  solution: false,
            },
            {
                  id: 44,
                  text: 'Поганий провід/клема який зєднує корпус генератора з мінусом акумулятора. Якщо у вас стартер повільно крутить двигун, причина цьому може бути цей провід/клему.',
                  solution: false,
            },
            {
                  id: 45,
                  text: 'Поганий провід/клема який зєднує плюсову клему генератора з плюсом акумулятора.',
                  solution: false,
            },
            {
                  id: 46,
                  text: 'Генератор не справляється з нагрузкою на холостих обертах. Причини: генератор не справний; генератор малопотужний; акумулятор розряджений, або стоїть більшої ємності ніж визначено заводом; ремінь генератора не натягнутий (можливий писк ремня, а також шків буде нагріватись після роботи);',
                  solution: false,
            },
            {
                  id: 47,
                  text: 'Провід який зєднує корпус генератора з мінусом акумулятора добрий.',
                  solution: false,
            },
            {
                  id: 48,
                  text: 'Провід який зєднує плюсову клему генератора з плюсом акумулятора добрий.',
                  solution: false,
            },
            {
                  id: 49,
                  text: 'У вас губиться напруга від генератора до акумулятора. Рекомендуємо спочатку усунути цю проблему. У нас є діагностика цієї проблеми (Мала напруга на акумуляторі).',
                  solution: false,
            },
            {
                  id: 50,
                  text: 'У Вас генератор не дає напругу взагалі (нема заряду акумулятора). Рекомендуємо спочатку усунути цю проблему у спеціаліста, адже потрібні знання з електрики вашого авто.',
                  solution: false,
            },
            {
                  id: 51,
                  text: 'При збільшенні обертів двигуна шум збільшується, це означає, що шум йде від якогось підшипника.',
                  solution: false,
            },
            {
                  id: 52,
                  text: 'Шум на холостих обертах означає підозру виходу з ладу шківа генератора.',
                  solution: false,
            },
            {
                  id: 53,
                  text: 'Генератор не дає напругу, якщо з шківом не пропускає в обидві сторони це означає, що генератор не справинй.',
                  solution: false,
            },
            {
                  id: 54,
                  text: 'Шків  працює добре.',
                  solution: false,
            },
            {
                  id: 55,
                  text: 'Шків  заклинив, через це буде підскакувати натяжний механізм і він з часом вийде з ладу (скине ремінь і можливо щось пошкодиться). Також може виникати шум на холостих обертах. Його потрідно замінити. Для цього потрібен спеціальний ключ та пневмогайковерт (технологія яку ви можете найти в інтернеті з ключем та бітою торксом, може відкрутити шківа ,але якщо він був заклинений Ви можете пошкодити якір генератора який прийдеться замінити разом з шківом). Якщо у вас нема такого іструменту зверніться до нас, зазвичай приходиться знімати генератор з двигуна. Ви можете самі його зняти і принести до нас для заміни шківа. Рекомендований шків оригінальної фірми INA, або оригінал Litens.',
                  solution: false,
            },
            {
                  id: 56,
                  text: 'Шків  пропускає в обидві сторони, через це генератор не буде давати напругу. Інколи може виникати шум скреготу. Його потрідно замінити. Для цього потрібен спеціальний ключ та пневмогайковерт (технологія яку ви можете найти в інтернеті з ключем та бітою торксом, може відкрутити шківа ,але якщо він був заклинений Ви можете пошкодити якір генератора який прийдеться замінити разом з шківом). Якщо у вас нема такого іструменту зверніться до нас, зазвичай приходиться знімати генератор з двигуна. Ви можете самі його зняти і принести до нас для заміни шківа. Рекомендований шків оригінальної фірми INA, або оригінал Litens.',
                  solution: false,
            },
            {
                  id: 57,
                  text: 'В генераторі зношені підшипники. Потрібно їх замінити.',
                  solution: false,
            },
            {
                  id: 58,
                  text: 'Обводні роліки зношені, їх потрібно замінити.',
                  solution: false,
            },
            {
                  id: 59,
                  text: 'Є підозра, що шків генератора заклинив, адже натяжний механізм ніколи не має підскакувати, якщо шків справний.',
                  solution: false,
            },
            {
                  id: 60,
                  text: 'Стертий шків потрібно замінити бо ремінь може по ньому ковзати і створювати шум.',
                  solution: false,
            },
            {
                  id: 61,
                  text: 'Пошкоджений ремінь треба замінити, щоб він не порвався, також через нього може бути шум.',
                  solution: false,
            },
            {
                  id: 62,
                  text: 'Спробуйте підтягнути ремінь, можливо шум на холостих зникне.',
                  solution: false,
            },
            {
                  id: 63,
                  text: 'Без ареометра сладно визначити стан акумулятора в середині.',
                  solution: false,
            },
            {
                  id: 64,
                  text: 'Через те що від замка запалювання нема сигнала стартер не запускається. Перевірте реле стартера, запобіжники або замок запалювання. Спробуйте повернути замок в положенння пуску і шивелити ключем (якщо стартер працюватиме, замок потрібно замінити).',
                  solution: false,
            },
            {
                  id: 65,
                  text: 'У вас не працює стартер (його потрібно демонтувати та розібрати), також від замка запалювання нема сигнала тому стартер не запускаєтиметься після ремонту. Перевірте реле стартера, запобіжники або замок запалювання. Спробуйте повернути замок в положенння пуску і шивелити ключем (якщо сигнал на малій клемі появиться, замок потрібно замінити). Також перевірте щоб замок самостійно повертався з положення пуску двигуна в положення влюченого запалювання (якщо так не робиться то замініть замок).',
                  solution: false,
            },
            {
                  id: 66,
                  text: 'У вас не працює стартер (його потрібно демонтувати та розібрати). Також перевірте щоб замок самостійно повертався з положення пуску двигуна в положення влюченого запалювання (якщо так не робиться то замініть замок).',
                  solution: false,
            },
            {
                  id: 67,
                  text: 'У вас поганий провід який йде від замка запалювання до малої клеми стартера, або поганий замок, чи реле стартера. Можете поставити розвантажувальне реле на сигнальний провід від замка яке вмикатиме силовий плюс на малу клему стартера.',
                  solution: false,
            },
            {
                  id: 68,
                  text: "Якщо глибина зносу колектора 0.6мм - це залишилось 30% ресурсу. 1мм -це весь ресурс використано, генератор вже перестав давати зарядку або скоро перестане.",
                  solution: false,
            },
            {
                  id: 69,
                  text: "У Вас проблеми з стартером, можливо кінчаються щітки або погана маса на корпусі. Якщо у Вас стартера фірми Mitsubishi однозначно знімайте та робіть профілактику, ці стартера мають заводські дефекти маси.",
                  solution: false,
            },
            {
                  id: 70,
                  text: "Щітки кінчились, їх потрібно замінити (приварити нові).",
                  solution: false,
            },
            {
                  id: 71,
                  text: "Якір пошкоджений, його потрібно замінити.",
                  solution: false,
            },
            {
                  id: 72,
                  text: "Втягуюче потрібно замінити адже воно вичерпало свій ресурс",
                  solution: false,
            },
            {
                  id: 73,
                  text: "Поганий провід/клема (+) який йде від плюсової клеми акумулятора до товстого болта на старері. Виправте спочатку цю ситуацію.",
                  solution: false,
            },
            {
                  id: 74,
                  text: "Втягуюче не перемикає в собі контакти, його потрібно замінити",
                  solution: false,
            },
            {
                  id: 75,
                  text: "В обхід втягуючого стартер працює, одже з робочим втягуючим він мусить працювати.",
                  solution: false,
            },
            {
                  id: 76,
                  text: "В обхід втягуючого стартер не працює, схоже що в стартері проблема більша ніж не робоче втягуюче. Потрібно демонтувати та розбирати.",
                  solution: false,
            },
            {
                  id: 77,
                  text: "Дивно що все працює добре. Якщо ваш стартер дійсно клацає коли повертати замок запалення тоді наші здогадки наступні. Стартер може працювати якщо подати + на малу клему втягуючого, це може означати: втягуюче зношене, реле стартера погане, поганий провід від замка запалення, поганий замок запалення. Можете поставити розвантажувальне реле на сигнальний провід від замка яке вмикатиме силовий плюс на малу клему стартера, але якщо втягуюче погане це допоможе на малий проміжок часу. ",
                  solution: false,
            },
            {
                  id: 78,
                  text: "Без мультиметра ви нічого не виясните. Знайдіть десь його та почніть діагностику.",
                  solution: false,
            }
      ]

}
export default serverData
