import img19 from "./../img/19.png"
import img15 from "./../img/15.png"
import img78 from "./../img/78.png"
import img77 from "./../img/77.png"


import video17 from "./../video/video17.mp4"
import video20 from "./../video/video20.mp4"

const serverData = {
      testCard:{
            1: {
                  linkNumber: 1.0,
                  problem: "Попередження!!! Під час проходження тесту не оновлюйте сторінку, це може призвезти до неправильних результатів діагностики.",
                  testText:'',
                  instruction:'',
                  linkNumberYes: 1.1,
                  linkNumberNo: 1.1,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.1: {
                  linkNumber: 1.1,
                  problem: "Дайте відповідь на питання",
                  testText:'Коли працює стартер, двигун провертається без зупинок? Так-означає, що стартер завжди провертає двигун без зупинок. Ні-означає, що коли стартер працює, двигун ніколи не обертається або інколи не обертається.',
                  instruction:'',
                  linkNumberYes: 6.5,
                  linkNumberNo: 1.2,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.2: {
                  linkNumber: 1.2,
                  problem: "Дайте відповідь на питання",
                  testText: 'Стартер провертає двигун на декілька обертів ,а потім починає крутитись в холосту, перестаючи проверти двигун?',
                  instruction:'',
                  linkNumberYes: 1.2_13_1,
                  linkNumberNo: 1.2_13_0,
                  solutionYes:1.8,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.2_13_1: {
                  linkNumber: `1.2_13_1${' Yes'}`,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чути як стартер працює,але мотор не крутиться?',
                  instruction:'',
                  linkNumberYes: 1.4,
                  linkNumberNo: 1.2,
                  solutionYes:1.8,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.2_13_0: {
                  linkNumber: `1.2_13_0${' No'}`,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чути як стартер працює,але мотор не крутиться?',
                  instruction:'',
                  linkNumberYes: 1.4,
                  linkNumberNo: 8,
                  solutionYes:1.8,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.3_66_1:{
                  linkNumber: `1.3_66_1${' No'}`,
                  problem: "Щось не так",
                  testText: 'Ви дали дві різні відповіді на одне питання, можливо ви помились або вам ця діагностика не підходить.',
                  instruction:'',
                  linkNumberYes: 1.1,
                  linkNumberNo: 1.1,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.4: {
                  linkNumber: 1.4,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час роботи стартера чути голосний гуркіт, скрегіт?',
                  instruction:'',
                  linkNumberYes: 6.7,
                  linkNumberNo: 6.7,
                  solutionYes:1.4,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            1.5: {
                  linkNumber: 1.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Зуби на стартері пошкодженні(дивіться інструкцію)?',
                  instruction:'Приклади пошкоджених бендиксів на фото (грані зубів можуть відрізнятись в залежності в яку сторонну крутиться бендикс)',
                  linkNumberYes: 1.9,
                  linkNumberNo: 1.9,
                  solutionYes:1.5,
                  solutionNo:1.0,
                  img: img15,
                  video: null,
            },
            1.7: {
                  linkNumber: 1.7,
                  problem: "Дайте відповідь на питання",
                  testText: 'У вас вінець рухається окремо від маховика (дивіться інструкцію)?',
                  instruction:"На відео видно, що вінець з зубами крутяться окремо від маховика.",
                  linkNumberYes: 2.0,
                  linkNumberNo: 2.0,
                  solutionYes:1.7,
                  solutionNo:1.0,
                  img: null,
                  video: video17,
            },
            1.9: {
                  linkNumber: 1.9,
                  problem: "Дайте відповідь на питання",
                  testText: "Потрібно перевірити який стан зубів на вінцю маховика (дивіться інструкцію). Зуби на вінцю маховика пошкодженні?",
                  instruction:'Поставте мітку на маховику, прокручуйте колнчастий вал та дивіться на зуби на вінцю маховика. Прокручуйте колінчастий вал поки зробите повний оберт. Дивіться приклади на фото. ',
                  linkNumberYes: 1.7,
                  linkNumberNo: 1.7,
                  solutionYes:1.6,
                  solutionNo:1.0,
                  img: img19,
                  video: null,
            },
            2.0: {
                  linkNumber: 2.0,
                  problem: "Дайте відповідь на питання",
                  testText: 'Ваш бендикс крутиться легко(дивіться іннструкцію)?',
                  instruction:'Візьміть стартер в руки, пробуйте прокрутити бендикс, в один напрямок він мусить крутити з собою якір(але щоб це зробити потрібна велика сила, тому якщо він не провертається це теж показник ,що все добре) ,а в інший напрямок мусить крутитись лише сам бендикс(обовязково мусить крутись з легким супротивом). На відео бендикс крутиться без супротиву, це означає, що він ослаб.',
                  linkNumberYes: 7.9,
                  linkNumberNo: 2.1,
                  solutionYes:1.8,
                  solutionNo:1.0,
                  img: null,
                  video: video20,
            },
            2.1: {
                  linkNumber: 2.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Бендикс не працює як муфта, він заблокований в обидві строни, в жодну з сторін не провертається?',
                  instruction:'',
                  linkNumberYes: 6.9,
                  linkNumberNo: 6.9,
                  solutionYes:1.9,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            6.5: {
                  linkNumber: 6.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Під час роботи стартера чути шум, жужання, скрегіт, буксування?',
                  instruction:'',
                  linkNumberYes: 6.7,
                  linkNumberNo: 6.6,
                  solutionYes:1.4,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            6.6: {
                  linkNumber: 6.6,
                  problem: "Проблем не виявленно",
                  testText: 'Можливо у вас нема проблем в даний час, або ви просто не ту діагностику провели.',
                  instruction:'',
                  linkNumberYes: 1.1,
                  linkNumberNo: 1.1,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            6.7: {
                  linkNumber: 6.7,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щоб вияснити що у вас вийшло з ладу потрібно демонтувати стартер. Вам до снаги така задача?',
                  instruction:'',
                  linkNumberYes: 6.8,
                  linkNumberNo: 7.6,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            6.8: {
                  linkNumber: 6.8,
                  problem: "Потрібно зловити момент коли стартер шумить або не провертає двигун, і тоді його демонтувати.",
                  testText: '',
                  instruction:'',
                  linkNumberYes: 1.5,
                  linkNumberNo: 1.5,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            6.9: {
                  linkNumber: 6.9,
                  problem: "Дайте відповідь на питання",
                  testText: 'Щоб вияснити ,що у вас вийшло з ладу потрібно розібрати стартер. Якщо ваший стартер фірми Mitsubishi , рекомендуєм його розібирати спеціалізованому сервісу , адже ці стартера мають заводський дефект (тільки фірма Mitsubishi), через який він розбирається з великими проблемами. Вам до снаги задача розібрати стартер?',
                  instruction:'',
                  linkNumberYes: 7.2,
                  linkNumberNo: 7.6,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            7.0: {
                  thet:"компонетнт з результатом"
                  // linkNumber: 7.0,
                  // problem: "Ось що ви вияснили:",
                  // testText: '',
                  // linkNumberYes: 7.0,
                  // linkNumberNo: 7.0,
                  // solutionYes:null,
                  // solutionNo:null,
                  // img: null,
                  // video: null,
            },
            7.1: {
                  linkNumber: 7.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чи пошкодженна ізоляція на якорі?',
                  instruction:'',
                  linkNumberYes: 7.4,
                  linkNumberNo: 7.4,
                  solutionYes:2.3,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            7.2: {
                  linkNumber: 7.2,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вісь у втулках має великий люфт?',
                  instruction:'На вигляд (на око), зношені втулки мають овальний отвір',
                  linkNumberYes: 7.3,
                  linkNumberNo: 7.3,
                  solutionYes:2.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            7.3: {
                  linkNumber: 7.3,
                  problem: "Дайте відповідь на питання",
                  testText: 'Підшипники розвалилися, крутяться з ривками, шумлять?',
                  instruction:'',
                  linkNumberYes: 7.7,
                  linkNumberNo: 7.7,
                  solutionYes:2.1,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            7.4: {
                  linkNumber: 7.4,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вимийте редуктор від мастила. В ньому відсутні зуби, присутні тріщини, пошкодження?',
                  instruction:'',
                  linkNumberYes: 7.0,
                  linkNumberNo: 7.5,
                  solutionYes:2.4,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            7.5: {
                  linkNumber: 7.5,
                  problem: "Дайте відповідь на питання",
                  testText: 'Вал в редукторі крутиться легко та без ривків?',
                  instruction:'',
                  linkNumberYes: 7.0,
                  linkNumberNo: 7.0,
                  solutionYes:1.0,
                  solutionNo:2.5,
                  img: null,
                  video: null,
            },
            7.6: {
                  linkNumber: 7.6,
                  problem: "Пропонуєм Вам вернутись до нашого сервісу.",
                  testText: '',
                  instruction:'',
                  linkNumberYes: null,
                  linkNumberNo: null,
                  solutionYes:null,
                  solutionNo:null,
                  img: null,
                  video: null,
            },
            7.7: {
                  linkNumber: 7.7,
                  problem: "Дайте відповідь на питання",
                  testText: 'Чи є на якорі сліди тертя об статор?',
                  instruction:'Сліди тертя блистять як метал натертий до блиску.На фото якір який терся об статор (відбликуюсть сліди тертя)',
                  linkNumberYes: 7.8,
                  linkNumberNo: 7.8,
                  solutionYes:2.2,
                  solutionNo:1.0,
                  img: img77,
                  video: null,
            },
            7.8: {
                  linkNumber: 7.8,
                  problem: "Дайте відповідь на питання",
                  testText: 'Магніти статора пошкодженні (дивіться інструкцію)? Якщо у вас не магніти, а катушка-чи пошкоджена ізоляція катушки?',
                  instruction:'',
                  linkNumberYes: 7.1,
                  linkNumberNo: 7.1,
                  solutionYes:1.2,
                  solutionNo:1.0,
                  img: img78,
                  video: null,
            },
            7.9: {
                  linkNumber: 7.9,
                  problem: "Дайте відповідь на питання",
                  testText: 'Бендикс крутиться в обидві сторони?',
                  instruction:'',
                  linkNumberYes: 6.9,
                  linkNumberNo: 6.9,
                  solutionYes:1.3,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            8: {
                  linkNumber: 8,
                  problem: "Дайте відповідь на питання",
                  testText: 'Коли замок повернутий положення стартера, чути як стастер часто клацає (дивіться інструкцію)?',
                  instruction:'На відео чути як працює стартер, у вас так само?',
                  linkNumberYes: 8.2,
                  linkNumberNo: 8.1,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            8.1: {
                  linkNumber: 8.1,
                  problem: "Дайте відповідь на питання",
                  testText: 'Коли замок повернутий положення стартера, на один поворот ключа чути як стастер один раз клацне (дивіться інструкцію)?',
                  instruction:'На відео стартер вмикають три рази. Стартер чути голосно, якщо клацає реле в блоці запобіжників то це буде тихо',
                  linkNumberYes: 8.2,
                  linkNumberNo: 1.3_66_1,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            8.2: {
                  linkNumber: 8.2,
                  problem: "Перше за все рекомендуєм зробити діагностику акумулятора",
                  testText: '',
                  instruction:'',
                  linkNumberYes: 8.3,
                  linkNumberNo: 8.3,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
            8.3: {
                  linkNumber: 8.3,
                  problem: "Діагностика акб",
                  testText: '',
                  instruction:'',
                  linkNumberYes: 8.3,
                  linkNumberNo: 8.3,
                  solutionYes:1.0,
                  solutionNo:1.0,
                  img: null,
                  video: null,
            },
      },
      resaultDiagnostic:{
            1.0:{
                  text:'Під час діагностики ніяких проблем не було знайдено, так не буває. Пройдіть діагностику ще раз та уважніше все передивіться.',
                  solution: false,
            },
            1.1:{
                  text:'',
                  solution: false,
            },
            1.2:{
                  text:'Якщо пошкоджені магніти - замінити цілий статор, якщо пошкоджена ізоляція катушки - розібрати статор, відновити ізоляцію (є ризик, що стане гірше навіть якщо ізоляцію відновити. Після розборки статора змінює форму і через це починає сильно чиркати якорь.) рекомендовано замінити статор повністю.',
                  solution: false,
            },
            1.3:{
                  text:'Бендикс не працює як муфта, він пропускає в обидві сторони. Його потрібно замінити.',
                  solution: false,
            },
            1.4:{
                  text:'Приділіть особливу увагу, зубам на бендиксі та вінцю маховика, вони не мусять бути пошкодженні. Також перевірте редуктор ,підшипники, та втулки.',
                  solution: false,
            },
            1.5:{
                  text:'На бендиксі пошкоджені зуби, його потрібно заміннити (якщо вам шкода грошей, або немає запчастин, і ви впевнені що муфта тримає навантаження ,і проблема лише в поганих зубах, просто загостріть їх, але ви повинні знати який мають вигляд цілі зуби) .',
                  solution: false,
            },
            1.6:{
                  text:'Пошкоджені зуби на вінцю маховика, потрібно замінити вінець маховика, або весь маховик з вінцем разом.',
                  solution: false,
            },
            1.7:{
                  text:'Вінець відділився від маховика. Таке буває дуууже рідко. Потрібно замінити маховик з вінцем разом, або приварити вінець до маховика.',
                  solution: false,
            },
            1.8:{
                  text:'Є підозра що бендикс дуже зношений, його потрібно замінити щоб перестрахуватись.',
                  solution: false,
            },
            1.9:{
                  text:'Бендикс заклинив, можливо в нього попала вода. Потрібно його замінити.',
                  solution: false,
            },
            2.0:{
                  text:'У втулках вісь має великий люфт, втулки потрібно замінити.',
                  solution: false,
            },
            2.1:{
                  text:'Підшипники пошкодженні, їх потрібно замінити.',
                  solution: false,
            },
            2.2:{
                  text:'На якорі є сліди тертя об статор,якщо ви ще не перевірили втулки і підшипники то зробіть це.',
                  solution: false,
            },
            2.3:{
                  text:'На якорі пошкодженна ізоляція, через це стартер може повільно працювати, може працювати з перебоями, або не працювати взагалі. Якір потрібно замінити.',
                  solution: false,
            },
            2.4:{
                  text:'Редуктор пошкоджений, його потрібно замінити.',
                  solution: false,
            },
            2.5:{
                  text:'Потрібно вичистити кожеш зуб редуктора, поки вал не буде крутитись легко без ривків. Якщо не вдається замінити редуктор.',
                  solution: false,
            },
      
      }
      
}
export default serverData
